apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-connection-logger
  labels:
    app: db-connection-logger
    purpose: log-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-connection-logger
  template:
    metadata:
      labels:
        app: db-connection-logger
        purpose: log-generation
    spec:
      containers:
      - name: db-logger
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          # Generate logs at 10 logs/second
          # Sleep for 0.10 seconds between logs (1/  = 0.02)
          
          while true; do
            # Generate a random user number between 1-1000
            user_num=$((RANDOM % 1000 + 1))
            echo "User$user_num has connected to the database"
            sleep 0.10
          done
